#+title: Index
#+created: 2020-09-25
#+roam_alias:
#+filetags:

* About these notes
Hello, I'm [[file:about-me.org][Yosevu Kilonzo]]. These are my notes. I write them in [[https://www.gnu.org/software/emacs/][Emacs]] [[https://orgmode.org/][Org-mode]] and I publish them with [[https://firn.theiceshelf.com/][Firn]]. Find [[https://github.com/yosevu/notes.yosevu.com][the source code]] on GitHub. They are inspired by [[https://notes.andymatuschak.org/About_these_notes][Andy's working notes]].

I use [[https://www.orgroam.com/][Org-roam]], a [[file:note-taking.org][note-taking]] system and [[file:tools-for-thinking-functionally.org][tool for thought]] based on [[https://en.wikipedia.org/wiki/Zettelkasten][Zettelkasten]]. The system was popularized by German sociologist [[https://en.wikipedia.org/wiki/Niklas_Luhmann][Niklas Luhmann]] in the book [[file:how-to-take-smart-notes.org][How to Take Smart Notes]] by Sönke Ahrens. /Zettelkasten/ is usually translated as /slip box/, "slip" in the sense of a small piece of paper, a note.

The core idea is to [[file:use-your-brain-for-what-it-is-good-at.org][use your brain for what it is good at]]: networked thought.

Zettelkasten is a system for networked thought analogous to a neural network. Writing in the slip box is the fundamental tool for thinking. It is different than the traditional writing process because it is non-linear and allows for the emergence of creative insight.

This is my slip box. This is where I write. This is where I think. Find me on  me on [[https://twitter.com/yosevu][Twitter]], [[https://github.com/yosevu][GitHub]], and [[https://www.linkedin.com/in/yosevu][LinkedIn]] or email <a href="mailto:yosevu@yosevu.com">yosevu@yosevu.com</a> and let me know what you think!

* Pages
- [[file:about-me.org][About me]]
- [[file:projects.org][Projects]]
- [[file:learning-journal.org][Learning Journal]]

* Notes
- [[file:4clojure-exercises.org][4Clojure Exercises]]
- [[file:how-to-take-smart-notes.org][How to Take Smart Notes]]
- [[file:note-taking.org][Note-taking]]
- [[file:tools-for-thinking-functionally.org][Tools for Thinking Functionally]]
- [[file:use-your-brain-for-what-it-is-good-at.org][Use your brain for what it's good at]]